# Generated by Django 4.0.4 on 2022-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('used',)},
        ),
        migrations.AddField(
            model_name='question',
            name='used',
            field=models.IntegerField(default=1),
        ),
    ]
